#tested with g++ 7.3.0 (MSYS2 build) mingw-w64 and mingw32-make

example:
	g++ --std=c++11 example.cpp swarm.cpp -o example.exe
	
debug:
	g++   --std=c++11 -g example.cpp swarm.cpp -o d_example.exe
	
clean:
	del *.exe || rm *.exe
	
	
