#tested with g++ 7.2.0 mingw-w64 and mingw32-make

example:
	g++ -Wall -O3 --std=c++11 -I. C:\Windows\System32\OpenCL.dll memwrite.cpp -o memwrite.exe
	
debug:
	g++   --std=c++11 -g -Og -I. C:\Windows\System32\OpenCL.dll memwrite.cpp -o d_memwrite.exe
