dclex:
	echo R^"( > kernelstring.cl
	type kernels.cl >> kernelstring.cl
	echo )^" >> kernelstring.cl
	g++ -Og -g -Wall clswarmex.cpp clswarm.cpp misc.cpp C:\Windows\System32\OpenCL.dll -o clexample.exe
